//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping.Models.Siniflar
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomesSahibinden
    {
        public int ID { get; set; }
        public int price { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string age { get; set; }
        public string floor { get; set; }
        public string room { get; set; }
        public string metre { get; set; }
        public string district { get; set; }
        public string totalFloor { get; set; }
        public string heating { get; set; }
        public string isFurnished { get; set; }
        public string formHousing { get; set; }
        public string bathroom { get; set; }
        public string link { get; set; }
        public string image { get; set; }
    }
}
